In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
0,45654403,13328,1399,LEXUS,RX 450,2010.0,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,12.0
1,44731507,16621,1018,CHEVROLET,Equinox,2011.0,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black,8.0
2,45774419,8467,-,HONDA,FIT,2006.0,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black,2.0
3,45769185,3607,862,FORD,Escape,2011.0,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White,0.0
4,45809263,11726,446,HONDA,FIT,2014.0,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9155,45810592,16778,765,CHEVROLET,Orlando,2015.0,Jeep,Yes,LPG,2,34328 km,4.0,Automatic,Front,04-May,Left wheel,Grey,4.0
9156,45068478,26657,777,MAZDA,CX-5,2014.0,Jeep,No,Petrol,2.5,101435 km,4.0,Automatic,Front,04-May,Left wheel,Black,10.0
9157,45686742,21953,1327,NISSAN,X-Terra,2011.0,Jeep,Yes,Petrol,4,79633 km,6.0,Automatic,4x4,04-May,Left wheel,Silver,6.0
9158,45810532,22357,640,CHEVROLET,Orlando,2013.0,Jeep,Yes,Diesel,2,121042 km,4.0,Automatic,Front,04-May,Left wheel,White,4.0
9159,45768392,156,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9160 entries, 0 to 9159
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                9160 non-null   int64
 1   Price             9160 non-null   int64
 2   Levy              9159 non-null   object
 3   Manufacturer      9159 non-null   object
 4   Model             9159 non-null   object
 5   Prod. year        9159 non-null   float64
 6   Category          9159 non-null   object
 7   Leather interior  9159 non-null   object
 8   Fuel type         9159 non-null   object
 9   Engine volume     9159 non-null   object
 10  Mileage           9159 non-null   object
 11  Cylinders         9159 non-null   float64
 12  Gear box type     9159 non-null   object
 13  Drive wheels      9159 non-null   object
 14  Doors             9159 non-null   object
 15  Wheel             9159 non-null   object
 16  Color             9159 non-null   object
 17  Airbags           9159 non-null   float64
dtypes: float64(3), int64(2), object(13)
memory usage: 1.3+ MB

In [5]:
df.columns

Index(['ID', 'Price', 'Levy', 'Manufacturer', 'Model', 'Prod. year',
       'Category', 'Leather interior', 'Fuel type', 'Engine volume', 'Mileage',
       'Cylinders', 'Gear box type', 'Drive wheels', 'Doors', 'Wheel', 'Color',
       'Airbags'],
      dtype='object')

In [6]:
df.isnull().sum()

ID                  0
Price               0
Levy                1
Manufacturer        1
Model               1
Prod. year          1
Category            1
Leather interior    1
Fuel type           1
Engine volume       1
Mileage             1
Cylinders           1
Gear box type       1
Drive wheels        1
Doors               1
Wheel               1
Color               1
Airbags             1
dtype: int64

In [7]:
df['Color'].unique()

array(['Silver', 'Black', 'White', 'Grey', 'Blue', 'Green', 'Red',
       'Sky blue', 'Orange', 'Yellow', 'Brown', 'Golden', 'Beige',
       'Carnelian red', 'Purple', 'Pink', nan], dtype=object)

In [8]:
len(df['Color'].unique())

17

In [9]:
df[['ID', 'Manufacturer', 'Airbags', 'Price']].isnull().sum()

ID              0
Manufacturer    1
Airbags         1
Price           0
dtype: int64

In [10]:
df.iloc[:999, 0:17]

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color
0,45654403,13328,1399,LEXUS,RX 450,2010.0,Jeep,Yes,Hybrid,3.5,186005 km,6.0,Automatic,4x4,04-May,Left wheel,Silver
1,44731507,16621,1018,CHEVROLET,Equinox,2011.0,Jeep,No,Petrol,3,192000 km,6.0,Tiptronic,4x4,04-May,Left wheel,Black
2,45774419,8467,-,HONDA,FIT,2006.0,Hatchback,No,Petrol,1.3,200000 km,4.0,Variator,Front,04-May,Right-hand drive,Black
3,45769185,3607,862,FORD,Escape,2011.0,Jeep,Yes,Hybrid,2.5,168966 km,4.0,Automatic,4x4,04-May,Left wheel,White
4,45809263,11726,446,HONDA,FIT,2014.0,Hatchback,Yes,Petrol,1.3,91901 km,4.0,Automatic,Front,04-May,Left wheel,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,45647961,94,1058,MERCEDES-BENZ,ML 350,2012.0,Jeep,Yes,Diesel,3.5,224118 km,6.0,Automatic,4x4,04-May,Left wheel,White
995,45809896,12607,503,TOYOTA,Aqua,2012.0,Hatchback,Yes,Petrol,1.5,157160 km,4.0,Automatic,Front,04-May,Left wheel,Blue
996,45740308,9095,-,HONDA,Cr-v,2002.0,Jeep,Yes,CNG,2,187000 km,4.0,Manual,4x4,04-May,Right-hand drive,Silver
997,45813829,3058,1083,DODGE,Challenger,2013.0,Coupe,Yes,Petrol,3.6,232853 km,6.0,Automatic,Rear,02-Mar,Left wheel,Black
998,45815368,6899,-,HONDA,Stream,2004.0,Minivan,No,Petrol,1.7,0 km,4.0,Automatic,Front,04-May,Right-hand drive,Silver

In [11]:
df.columns

Index(['ID', 'Price', 'Levy', 'Manufacturer', 'Model', 'Prod. year',
       'Category', 'Leather interior', 'Fuel type', 'Engine volume', 'Mileage',
       'Cylinders', 'Gear box type', 'Drive wheels', 'Doors', 'Wheel', 'Color',
       'Airbags'],
      dtype='object')

In [13]:
df.dtypes

ID                    int64
Price                 int64
Levy                 object
Manufacturer         object
Model                object
Prod. year          float64
Category             object
Leather interior     object
Fuel type            object
Engine volume        object
Mileage              object
Cylinders           float64
Gear box type        object
Drive wheels         object
Doors                object
Wheel                object
Color                object
Airbags             float64
dtype: object

In [14]:
df['ID'] = df['ID'].astype(float)

In [15]:
df['ID']

0       45654403.0
1       44731507.0
2       45774419.0
3       45769185.0
4       45809263.0
           ...
9155    45810592.0
9156    45068478.0
9157    45686742.0
9158    45810532.0
9159    45768392.0
Name: ID, Length: 9160, dtype: float64

In [16]:
df['ID'] = df['ID'].astype(int)

In [17]:
df['ID']

0       45654403
1       44731507
2       45774419
3       45769185
4       45809263
          ...
9155    45810592
9156    45068478
9157    45686742
9158    45810532
9159    45768392
Name: ID, Length: 9160, dtype: int64

In [18]:
#Display stats of entire data
df.describe(include='all')

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
count,9.160000e+03,9160.000000,9159,9159,9159,9159.000000,9159,9159,9159,9159,9159,9159.000000,9159,9159,9159,9159,9159,9159.000000
unique,NaN,NaN,441,60,1051,NaN,11,2,6,98,4336,NaN,4,3,3,2,16,NaN
top,NaN,NaN,-,TOYOTA,Sonata,NaN,Sedan,Yes,Petrol,2,0 km,NaN,Automatic,Front,04-May,Left wheel,Black,NaN
freq,NaN,NaN,2772,1813,528,NaN,4186,6601,4907,1864,343,NaN,6446,6148,8711,8424,2399,NaN
mean,4.557738e+07,17242.530568,NaN,NaN,NaN,2010.896823,NaN,NaN,NaN,NaN,NaN,4.590457,NaN,NaN,NaN,NaN,NaN,6.623212
std,9.055381e+05,21382.316655,NaN,NaN,NaN,5.643379,NaN,NaN,NaN,NaN,NaN,1.216416,NaN,NaN,NaN,NaN,NaN,4.302453
min,2.470192e+07,1.000000,NaN,NaN,NaN,1943.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000
25%,4.570927e+07,5331.000000,NaN,NaN,NaN,2009.000000,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,4.000000
50%,4.577201e+07,13172.000000,NaN,NaN,NaN,2012.000000,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,6.000000
75%,4.580200e+07,22074.750000,NaN,NaN,NaN,2014.000000,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,NaN,NaN,NaN,NaN,12.000000
max,4.581665e+07,872946.000000,NaN,NaN,NaN,2020.000000,NaN,NaN,NaN,NaN,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,16.000000

In [19]:
#Stats of Numerical data
df.describe()

                 ID          Price   Prod. year    Cylinders      Airbags
count  9.160000e+03    9160.000000  9159.000000  9159.000000  9159.000000
mean   4.557738e+07   17242.530568  2010.896823     4.590457     6.623212
std    9.055381e+05   21382.316655     5.643379     1.216416     4.302453
min    2.470192e+07       1.000000  1943.000000     1.000000     0.000000
25%    4.570927e+07    5331.000000  2009.000000     4.000000     4.000000
50%    4.577201e+07   13172.000000  2012.000000     4.000000     6.000000
75%    4.580200e+07   22074.750000  2014.000000     4.000000    12.000000
max    4.581665e+07  872946.000000  2020.000000    16.000000    16.000000

In [21]:
#length of numerical dta columns count
len(df.describe())

8

In [22]:
#Stats of Object data
df.describe(include='object')

,Levy,Manufacturer,Model,Category,Leather interior,Fuel type,Engine volume,Mileage,Gear box type,Drive wheels,Doors,Wheel,Color
count,19237,19237,19237,19237,19237,19237,19237,19237,19237,19237,19237,19237,19237
unique,559,65,1590,11,2,7,107,7687,4,3,3,2,16
top,-,HYUNDAI,Prius,Sedan,Yes,Petrol,2,0 km,Automatic,Front,04-May,Left wheel,Black
freq,5819,3769,1083,8736,13954,10150,3916,721,13514,12874,18332,17753,5033

In [23]:
#length of object columns
len(df.describe(include='object').columns)

13

In [24]:
#duplicates count
print(df.duplicated().sum())

313

In [25]:
#drop duplicates
df = df.drop_duplicates()

In [26]:
print(df.duplicated().sum())

0

In [27]:
#display shape (rows and columns)
df.shape

(18924, 18)

In [28]:
df.columns

Index(['ID', 'Price', 'Levy', 'Manufacturer', 'Model', 'Prod. year',
       'Category', 'Leather interior', 'Fuel type', 'Engine volume', 'Mileage',
       'Cylinders', 'Gear box type', 'Drive wheels', 'Doors', 'Wheel', 'Color',
       'Airbags'],
      dtype='object')

In [29]:
#All the unique values from all the columns
for col in df.columns:
  print(f"{col} : {df[col].nunique()} unique values.")

ID : 18924 unique values.
Price : 2315 unique values.
Levy : 559 unique values.
Manufacturer : 65 unique values.
Model : 1590 unique values.
Prod. year : 54 unique values.
Category : 11 unique values.
Leather interior : 2 unique values.
Fuel type : 7 unique values.
Engine volume : 107 unique values.
Mileage : 7687 unique values.
Cylinders : 13 unique values.
Gear box type : 4 unique values.
Drive wheels : 3 unique values.
Doors : 3 unique values.
Wheel : 2 unique values.
Color : 16 unique values.
Airbags : 17 unique values.

In [34]:
df.sample(5)

,ID,Price,Levy,Manufacturer,Model,Prod. year,Category,Leather interior,Fuel type,Engine volume,Mileage,Cylinders,Gear box type,Drive wheels,Doors,Wheel,Color,Airbags
13903,45525725,19757,-,KIA,Optima,2014,Sedan,No,Hybrid,2.4,0 km,4.0,Tiptronic,Front,04-May,Left wheel,Blue,12
7777,45797751,19089,583,HYUNDAI,Elantra,2011,Sedan,Yes,Petrol,1.6,77483 km,4.0,Automatic,Front,04-May,Left wheel,Silver,4
7458,45768602,13350,-,TOYOTA,Aqua,2013,Sedan,No,Hybrid,1.5,1000 km,4.0,Automatic,Front,04-May,Right-hand drive,White,6
1279,45641362,3763,779,TOYOTA,Camry,2013,Sedan,Yes,Hybrid,2.5,124912 km,4.0,Automatic,Front,04-May,Left wheel,White,12
16962,45652867,392,831,HYUNDAI,Sonata,2011,Sedan,Yes,Hybrid,2.4,0 km,4.0,Automatic,Front,04-May,Left wheel,Silver,0